name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3. Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r marketplace/requirements.txt

      # 4. Run all tests with coverage (from marketplace folder)
      - name: Run Tests with Coverage
        working-directory: marketplace
        env:
          DJANGO_SETTINGS_MODULE: marketplace.settings
          PYTHONPATH: .
          OIDC_RP_CLIENT_ID: ${{ secrets.OIDC_RP_CLIENT_ID }}
          OIDC_RP_CLIENT_SECRET: ${{ secrets.OIDC_RP_CLIENT_SECRET }}
          OIDC_OP_ISSUER: ${{ secrets.OIDC_OP_ISSUER }}
          OIDC_OP_AUTHORIZATION_ENDPOINT: ${{ secrets.OIDC_OP_AUTHORIZATION_ENDPOINT }}
          OIDC_OP_TOKEN_ENDPOINT: ${{ secrets.OIDC_OP_TOKEN_ENDPOINT }}
          OIDC_OP_USER_ENDPOINT: ${{ secrets.OIDC_OP_USER_ENDPOINT }}
          OIDC_OP_JWKS_ENDPOINT: ${{ secrets.OIDC_OP_JWKS_ENDPOINT }}
          OIDC_RP_SIGN_ALGO: ${{ secrets.OIDC_RP_SIGN_ALGO }}
          AFRICASTALKING_USERNAME: ${{ secrets.AFRICASTALKING_USERNAME }}
          AFRICASTALKING_API_KEY: ${{ secrets.AFRICASTALKING_API_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

        run: |
          pytest --cov=. --cov-report=term-missing

      # 5. Build Docker image
      - name: Build Docker Image
        run: docker build -t my-django-app marketplace/.

      # 6. Trigger Render deployment
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/deploy/srv-XXXXXX" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer $RENDER_API_KEY"
